version: '3.4'

services:
  nginx:
    image: nginx:1.19
    ports:
      - "81:80"
    volumes:
      - .:/app
      - ${NGINX_CONF_PATH:-./docker/nginx/conf.d}:/etc/nginx/conf.d
  php:
    build:
      context: ./docker/php
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=127.0.0.1}
    volumes:
      - .:/app
      - ${PHP_INI_PATH:-./docker/php/conf.d/php.ini}:/usr/local/etc/php/conf.d/php.ini
      - ${DEBUG_INI_PATH:-./docker/php/conf.d/xdebug.ini}:/usr/local/etc/php/conf.d/xdebug.ini
  mysql:
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
